name: Add assignee to PR

on:
  pull_request:
    types: [opened]

jobs:
  add-assignee-to-pr:
    permissions:
      pull-requests: write
    uses: masutaka/actions/.github/workflows/add_assignee_to_pr.yml@main
